//КАТЕГОРИИ РАЗНЫХ ПОНЯТИЙ

const foodNames = [
	"cupcake", "cupcakes",
	"berry", "berries",
	"smurfberries", "smurfberry",
	"sarsaparilla",
	"butter",
	"tea",
	"estragon",
	"liquorice",
	"fries",
	"burger", "burgeers",
	"steak", "steaks",
	"potato", "potatoes",
	"brownie",
	"sardines",
	"sardine",
	"cюрстрёмминг",
	"cюрстремминг",
	"surströmming",
	"cola",
	"soda",
	"rice",
	"pasta",
	"asparagus",
	"avacado",
	"alfalfa",
	"acorn",
	"almond",
	"arugala",
	"artichoke",
	"applesauce",
	"noodles",
	"antelope",
	"tuna",
	"albacore",
	"avocado",
	"roll",
	"bruscetta",
	"bacon",
	"beans",
	"bagels",
	"bean",
	"bbq",
	"bison",
	"barley",
	"beer",
	"bisque",
	"bluefish",
	"bread",
	"broccoli",
	"buritto",
	"babaganoosh",
	"cabbage",
	"cake",
	"celery",
	"cheese",
	"chicken",
	"catfish",
	"chips",
	"chocolate",
	"chowder",
	"clams",
	"coffee",
	"cookies",
	"corn",
	"cupcakes",
	'crab',
	'curry', 
	'cereal', 
	'chimichanga', 
	'dips', 
	'duck', 
	'dumplings', 
	'donuts', 
	'donut', 
	'eggs', 
	'egg', 
	'enchilada', 
	'eggrolls', 
	'muffins', 
	'muffin', 
	'edimame', 
	'sushi', 
	'fajita', 
	'falafel', 
	'fish', 
	'franks', 
	'fondu', 
	'toast', 
	'dip', 
	'garlic', 
	'ginger', 
	'gnocchi', 
	'goose', 
	'granola', 
	'grapes', 
	'guancamole', 
	'gumbo', 
	'grits', 
	'crackers', 
	'cracker', 
	'ham', 
	'halibut', 
	'hamburger', 
	'cheeseburgers', 
	'cheeseburger', 
	'honey', 
	'hashbrown', 
	'hummus', 
	'cream', 
	'stew', 
	'food', 
	'bread', 
	'jambalaya', 
	'jelly', 
	'jam', 
	'jerky', 
	'jalapeño', 
	'kale', 
	'kabobs', 
	'ketchup', 
	'kiwi', 
	'kidney', 
	'kingfish', 
	'lobster', 
	'lamb', 
	'linguine', 
	'lasagna', 
	'meatballs', 
	'moose', 
	'milk', 
	'milkshake', 
	'noodles', 
	'ostrich', 
	'pizza', 
	'pepperoni', 
	'porter', 
	'pancakes', 
	'quesadilla', 
	'quiche', 
	'reuben', 
	'spinach', 
	'spaghetti', 
	'tots', 
	'toast', 
	'venison', 
	'waffles', 
	'waffle', 
	'wine', 
	'walnuts', 
	'walnut', 
	'yogurt', 
	'ziti', 
	'zucchini', 
	'zander', 
	'zapiekanka', 
	'zarzuela', 
	'zeppole', 
	'zerde', 
	'ziti', 
	'zongzi', 
	'zoni', 
	'zucchini', 
	'zuccotto', 
	'zander',
	"cakes",
	"zucchini",
	"zigni",
	"ziti",
	"zimtsterne",
	"zaboca",
	"zhejiang",
	"zampone",
	"apple", "apples",
	"banana", "bananas",
	"orange", "oranges",
	"strawberry", "strawberries",
	"pear", "pears",
	"grape", "grapes",
	"watermelon", "watermelons",
	"kiwi", "kiwis",
	"peach", "peaches",
	"mango", "mangos",
	"lemon", "lemons",
	"lime", "limes",
	"cherry", "cherries",
	"blueberry", "blueberries",
	"pineapple", "pineapples",
	"apricot", "apricots",
	"plum", "plums",
	"grapefruit", "grapefruits",
	"pomegranate", "pomegranates",
	"melon", "melons",
	"strawberries", "strawberry",
	"raspberries", "raspberry",
	"blackberry", "blackberries",
	"kiwi", "kiwis",
	"cantaloupe", "cantaloupes",
	"nectarine", "nectarines",
	"tangerine", "tangerines",
	"fig", "figs",
	"lime", "limes",
	"coconut", "coconuts",
	"tomato", "tomatoes",
	"cucumber", "cucumbers",
	"carrot", "carrots",
	"lettuce", "lettuces",
	"pepper", "peppers",
	"potato", "potatoes",
	"onion", "onions",
	"pea", "peas",
	"bean", "beans",
	"broccoli", "broccolis",
	"zucchini", "zucchinis",
	"spinach", "spinachs",
	"garlic", "garlics",
	"squash", "squashes",
	"cabbage", "cabbages",
	"celery", "celeries",
	"eggplant", "eggplants",
	"mushroom", "mushrooms",
	"asparagus", "asparaguses",
	"avocado", "avocados",
	"artichoke", "artichokes",
	"pepper", "peppers",
	"corn", "corns",
	"radish", "radishes",
	"green bean", "green beans",
	"brussels sprout", "brussels sprouts",
	"cauliflower", "cauliflowers",
	"beet", "beets",
	"leek", "leeks",
	"parsnip", "parsnips",
	"lemon", "lemons",
	"pomelo", "pomelos",
	"clementine", "clementines",
	"rhubarb", "rhubarbs",
	"plantain", "plantains",
	"kale", "kales",
	"turnip", "turnips",
	"persimmon", "persimmons",
	"guava", "guavas",
	"locust", "locusts",
	"kumquat", "kumquats",
	"radicchio", "radicchios",
	"endive", "endives",
	"chives", "chive",
	"beef",
]
export{foodNames}
//еда
const foodDescription = [
	"delicious",
	"tasty",
	"satisfying",
	"flavorful",
	"nutritious",
	"mouthwatering",
	"crispy",
	"tender",
	"juicy",
	"savory",
	"spicy",
	"fresh",
	"homemade",
	"creamy",
	"zesty",
	"crunchy",
	"hearty",
	"famous",
	"exotic",
	"aromatic",
	"smoky",
	"rich",
	"buttery",
	"refreshing",
	"wholesome",
	"succulent",
	"fancy",
	"sweet",
	"sour",
	"zesty",
	"silky",
	"grilled",
	"roasted",
	"crumbly",
	"sizzling",
	"seasoned",
	"glazed",
	"frosty",
	"crusty",
	"chilled",
	"sizzling",
	"pickled",
	"tangy",
	"bubbly",
	"crunchy",
	"gooey",
	"fluffy",
	"golden",
	"scrumptious",
	"whipped",
	"tart",
	"exquisite",
	"charred",
	"fragrant",
	"syrupy",
	"crackling",
	"dripping",
	"baked",
	"smothered",
	"iced",
	"oozing",
	"tempting",
	"toasty",
	"bountiful",
	"sizzling",
	"hot",
	"cold",
	"spicy",
	"savory",
	"sweet",
	"crunchy",
	"fresh",
	"creamy",
	"tangy",
	"zesty",
	"smoky",
	"flavorful",
	"delicious",
	"juicy",
	"warm",
	"crispy",
	"tender",
	"satisfying",
	"rich",
	"savory",
	"wholesome",
	"frosty",
	"homemade",
	"crumbly",
	"buttery",
	"spicy",
	"hearty",
	"aromatic",
	"grilled",
]
export{foodDescription}
const foodQuestions = [
	"What's your favorite type of cuisine?",
	"Do you prefer sweet or savory dishes?",
	"Have you ever tried cooking a new recipe?",
	"Do you enjoy spicy food?",
	"What's the weirdest food you've ever tried?",
	"Are you a fan of fast food?",
	"Do you like to eat out or cook at home?",
	"Have you ever been to a food festival?",
	"Do you like to experiment with new flavors?",
	"What's your go-to comfort food?",
	"Do you have any dietary restrictions?",
	"Have you ever tried a food challenge?",
	"Do you enjoy trying different foods from around the world?",
	"What's your favorite dessert?",
	"Do you like to snack throughout the day?",
	"Have you ever eaten a dish that was too spicy for you?",
	"Do you like to pair food with wine or other beverages?",
	"Do you have a favorite food blogger or chef?",
	"What's your opinion on fusion cuisine?",
	"Do you believe in the saying 'you are what you eat'?",
	"Have you ever cooked for a large group of people?",
	"Do you follow any food trends?",
	"What's your favorite breakfast food?",
	"Do you like to pack your own lunch for work/school?",
	"Have you ever made your own pasta or bread from scratch?",
	"Do you enjoy trying street food when traveling?",
	"What's your favorite food holiday or celebration?",
	"Do you like to host dinner parties?",
	"Have you ever tried a food from a different culture that you didn't like?",
	"Do you like to donate to food banks or charities?",
	"What's your opinion on food waste?",
	"Do you have a favorite food-related movie or TV show?",
	"Is there a dish that reminds you of your childhood?",
	"Have you ever taken a cooking class?",
	"Do you have a favorite restaurant that you frequent?",
	"What's your go-to meal when you don't feel like cooking?",
	"Do you have a favorite food-related memory?",
	"Are you a fan of food documentaries?",
	"What's the most exotic food you've ever tried?",
	"Do you meal prep for the week ahead?",
	"Have you ever had a food allergy scare?",
	"Do you enjoy gardening or growing your own produce?",
	"What's your favorite food-related quote?",
	"Do you like to try new food products or brands?",
	"Have you ever participated in a food tasting event?",
	"Do you enjoy cooking with fresh ingredients or do you prefer convenience foods?",
]
export{foodQuestions}
//описание еды
const natureWords = [
	"stone", "stones",
	"tree",
	"sun",
	"river",
	"mountain",
	"clouds",
	"rain",
	"wind",
	"flower",
	"forest",
	"field",
	"lake",
	"sky",
	"grass",
	"sand",
	"dune",
	"valley",
	"canyon",
	"waterfall",
	"meadow",
	"desert",
	"island",
	"volcano",
	"tundra",
	"bamboo",
	"delta",
	"glacier",
	"lagoon",
	"reef",
	"cave",
	"plateau",
	"marsh",
	"pond",
	"summit",
	"rift",
	"fjord",
	"delta",
	"gulf",
	"savanna",
	"estuary",
	"cliff",
	"ridge",
	"stream",
	"hill",
	"bay",
	"quarry",
	"heath",
	"swamp",
	"ravine",
	"oasis",
	"crater",
	"basin",
	"promontory",
	"dell",
	"crag",
	"grove",
	"floodplain",
	"foothill",
	"quagmire",
	"arctic",
	"bush",
	"gorge",
	"fen",
	"knoll",
	"pinnacle",
	"escarpment",
	"alluvial",
	"estuary",
	"upland",
	"taiga",
	"saltmarsh",
	"crag",
	"tableland",
	"trellick",
	"wetland",
	"canyon",
	"wadi",
	"rainforest",
	"mesa",
	"prairie",
	"tropics",
	"arroyo",
	"bight",
	"trial",
	"cape",
	"isthmus",
	"moor",
	"foreland",
	"corrie",
	"polynya",
	"pocosin",
	"lava",
	"pebble",
	"gully"
]
export{natureWords}
const natureDescription = [
	"natural",
	"beautiful",
	"serene",
	"majestic",
	"vibrant",
	"scenic",
	"peaceful",
	"tranquil",
	"lush",
	"breathtaking",
	"pristine",
	"picturesque",
	"harmonious",
	"stunning",
	"refreshing",
	"idyllic",
	"spectacular",
	"calm",
	"gentle",
	"magnificent",
	"verdant",
	"exotic",
	"radiant",
	"fascinating",
	"dramatic",
	"abundant",
	"graceful",
	"colorful",
	"bountiful",
	"mysterious",
	"delightful",
	"fresh",
	"unspoiled",
	"ethereal",
	"silken",
	"vivid",
	"blissful",
	"inspiring",
	"lyrical",
	"abstract",
	"enchanting",
	"astounding",
	"captivating",
	"charming",
	"dreamy",
	"glorious",
	"invigorating",
	"mesmerizing",
	"wondrous",
	"radiant",
	"sublime",
	"vivacious",
	"peaceful",
	"tranquil",
	"luscious",
	"delicate",
	"fragrant",
	"serene",
	"enchanting",
	"mystical",
	"ethereal",
	"gentle",
	"whimsical",
	"soothing",
	"tranquil",
	"captivating",
	"enrapturing",
	"invigorating",
	"breathtaking",
	"ravishing",
	"splendid",
	"splendorous",
	"visually stunning",
	"rural",
	"cosmic",
	"panoramic",
	"serendipitous",
	"organic",
	"wonderous",
	"awe-inspiring",
	"awe-striking"
]
export{natureDescription}
const natureQuestions = [
	"What marvels of nature have you witnessed lately?",
	"Have you ever felt a connection to the earth?",
	"Do you find peace in the sounds of nature?",
	"How do you feel when you gaze at a starlit sky?",
	"Have you ever marveled at the beauty of a sunset?",
	"Do you believe in the healing power of nature?",
	"Have you ever felt a sense of wonder in the presence of a majestic tree?",
	"What is your favorite season and why?",
	"Do you feel a sense of freedom when you're out in nature?",
	"Have you ever been touched by the beauty of a rainbow?",
	"What is your favorite flower and why?",
	"Have you ever felt a deep connection to a particular landscape?",
	"Can you feel the energy of the earth beneath your feet?",
	"Do you enjoy the tranquility of a flowing river?",
	"Have you ever felt small in the vastness of nature?",
	"What animal do you feel most connected to?",
	"Have you ever been moved by the power of a thunderstorm?",
	"Do you believe nature has the power to heal the soul?",
	"What is your most cherished memory in nature?",
	"Do you feel a sense of awe in the presence of a waterfall?",
	"Have you ever been inspired by the resilience of a plant growing in harsh conditions?",
	"What do you most appreciate about the beauty of nature?",
	"Do you believe that nature holds the key to a peaceful mind?",
	"Have you ever felt a sense of renewal in the changing of seasons?",
	"Can you feel the heartbeat of the earth?",
	"What do you find most enchanting about the night sky?",
	"Have you ever felt a sense of unity with all living things in nature?",
	"Do you find solace in the quiet of a forest?",
	"What do you think nature can teach us about life?",
	"Have you ever felt a sense of wonder in the presence of a mountain?",
	"Do you believe that nature has a language all its own?",
	"What do you love most about being in nature?",
	"Have you ever been touched by the gentleness of a breeze?",
	"Do you feel a sense of harmony in the presence of a flower garden?",
	"What is your favorite sound in nature?",
	"Have you ever been captivated by the colors of a sunset?",
	"Do you believe in the power of nature to inspire creativity?",
	"What is your favorite place in nature and why?",
	"Have you ever felt a sense of gratitude for the beauty of the natural world?",
	"Do you find joy in the simplicity of a walk in the woods?",
	"What is your favorite element of nature – earth, air, fire, or water?",
	"Have you ever been moved by the graceful flight of a bird?",
	"Do you feel a connection to the wisdom of the natural world?",
	"What do you find most fascinating about the mysteries of nature?",
	"Have you ever been amazed by the intricacy of a spider's web?",
	"Do you believe in the magic of nature?",
	"What is your wish for the future of our planet?",
]
export{natureQuestions}
//описание природы
const waterWords = [
	"ocean",
	"waves",
	"current",
	"tide",
	"surf",
	"beach",
	"seashore",
	"seagull",
	"whale",
	"dolphin",
	"ship",
	"sailboat",
	"sail",
	"anchor",
	"lighthouse",
	"tropical",
	"shell",
	"coral",
	"reef",
	"coastline",
	"seafloor",
	"shoreline",
	"beacon",
	"marina",
	"buoy",
	"jetty",
	"harbor",
	"pier",
	"wave",
	"tsunami",
	"buccaneer",
	"shipwreck",
	"captain",
	"crew",
	"compass",
	"navigation",
	"sailing",
	"fisherman",
	"sinker",
	"net",
	"lobster",
	"channel",
	"freshwater",
	"seaweed",
	"foghorn",
	"wharf",
	"surfing",
	"beachcomber",
	"kayak",
	"paddle",
	"snorkeling",
	"underwater",
	"dive",
	"submarine",
	"cruise",
	"sandy",
	"swimming",
	"lifeboat",
	"vest",
	"pirate",
	"regatta",
	"siren",
	"shipyard",
	"rowing",
	"wetsuit",
	"overboard",
	"salty",
	"swell",
	"fisherman",
	"clam",
	"tidal",
	"aquarium",
	"maritime",
	"mackerel",
	"boat",
	"raft",
	"coastguard",
	"paddleboard",
	"fishing",
	"shipmate",
	"shipshape",
	"seafaring",
	"harpoon",
	"float",
	"flotation",
	"seaplane",
	"fishing",
	"rigging",
	"porthole",
	"locker",
	"sunk",
	"seaworthy",
	"rowboat",
	"oceanography",
	"sailing",
	"yacht",
	"deck",
	"swimming",
	"swimming",
	"seadog",
	"shipwrecked",
	"coastline",
	"estuary",
	"island",
	"schooner",
	"bottom",
	"galleon",
	"mermaid",
	"cliff",
	"sea",
	"nautical",
	"stormy",
	"fishmonger",
	"harbour",
	"dolphinarium",
	"urchin",
	"octopus",
	"lobster",
	"crab",
	"waterfront",
	"spray",
	"boating",
	"yachting",
	"regatta",
	"rafting",
	"paddle",
	"sailor",
	"boatyard",
	"aqua",
	"outboard",
	"dock",
	"ferry",
	"blowhole",
	"starboard",
	"keelhaul",
	"seawall",
	"tiller",
	"gimbal",
	"maritime",
	"shoals",
	"drift",
	"jib",
	"topsail",
	"fog",
	"sailcloth",
	"swim",
	"sailfish",
	"sandcastle",
	"kayak",
	"water",
	"trench",
	"hydrofoil",
	"zodiac",
	"yacht",
	"scuba",
	"boating",
	"hydrodynamics",
	"anchors",
	"mizzenmast",
	"bosun",
	"bulkhead",
	"binnacle",
	"shore",
	"overboard",
	"starfish",
	"seabird",
	"puffin",
	"tern",
	"gannet",
	"seal",
	"turtle",
	"jellyfish",
	"manatee",
	"otter",
	"orca",
	"dolphin",
	"whale",
	"kayaking",
	"diving",
	"snorkeling",
	"swimming",
	"surfboard",
	"bodyboarding",
	"parasailing",
	"waterpark",
	"nautical",
	"coastline",
	"stowaway",
	"sinking",
	"navy",
	"tugboat",
	"tidal",
	"coastal",
	"aquatic",
	"starfish",
	"mermaid",
	"breeze",
	"oceanic",
	"shell",
	"shipwreck",
	"maritime",
	"diving",
	"surfing",
	"boat",
	"coral",
	"reef",
	"nautical",
	"clam",
	"harbor",
	"tropical",
	"coastal",
	"port",
	"aquatic",
	"marine",
	"seafood",
	"marina",
	"docks",
	"whale",
	"whales",
	"dolphin",
	"fishing",
      ];
export{waterWords}
const waterQuestions = [
	"What creatures live in the depths of the ocean?",
	"Why is the ocean so salty?",
	"How do whales communicate with each other in the vast ocean?",
	"Do all fish swim in schools?",
	"Have you ever seen a jellyfish up close?",
	"What is the most fascinating fact about octopuses?",
	"How deep can a diver go into the ocean?",
	"What is the purpose of a coral reef?",
	"Have you ever explored a shipwreck on the ocean floor?",
	"Why are dolphins considered one of the most intelligent marine animals?",
	"What causes the tides to rise and fall?",
	"Do you know how many species of sharks exist in the ocean?",
	"Why do some fish have bioluminescent capabilities?",
	"Have you witnessed a whale breach out of the water before?",
	"What is the significance of marine conservation?",
	"How do sea turtles navigate through the vast ocean?",
	"What is the impact of pollution on marine life?",
	"Have you ever seen a manta ray glide gracefully through the water?",
	"Why are seahorses such unique marine creatures?",
	"What is the role of phytoplankton in the ocean's ecosystem?",
	"Do you know how deep the Mariana Trench is?",
	"Why do some marine animals migrate long distances?",
	"Have you ever visited a coral reef in person?",
	"What is the importance of mangrove forests in coastal areas?",
	"How do marine mammals stay warm in cold ocean waters?",
	"What adaptations do deep-sea creatures have to survive in extreme pressure environments?",
	"Have you ever gone snorkeling to observe underwater life?",
	"Why do some fish change color to blend in with their surroundings?",
	"What is the difference between a seal and a sea lion?",
	"What is the largest creature in the ocean?",
	"What is the role of kelp forests in the marine ecosystem?",
	"How do marine biologist study underwater life?",
	"Have you seen a sea otter use tools for foraging?",
	"Why are mangroves important for protecting coastal areas from erosion?",
	"What is the deepest part of the ocean called?",
	"Do all marine animals rely on the sun for energy?",
	"Why are coral reefs known as the rainforests of the sea?",
	"Have you ever witnessed a pod of dolphins swimming together in the ocean?",
	"What is the concept of ocean acidification?",
	"How do pelicans catch fish in the ocean?",
	"What is the difference between a whale shark and a great white shark?",
	"Why are sea cucumbers crucial for ocean health?",
	"What is the process of desalination and its impact on marine environments?",
	"Have you ever sailed on a boat across the open ocean?",
	"Why are seagulls often seen near coastlines and harbors?",
	"What is the allure of deep-sea exploration?",
	"Do you know how sharks sense their prey in the water?",
	"What is the importance of protecting marine sanctuaries?",
]
export{waterQuestions}
//вода
const animalWords = [
	"dog",
	"dogs",
	"cat",
	"cats",
	"elephant",
	"elephants",
	"lion",
	"lions",
	"tiger",
	"tigers",
	"giraffe",
	"giraffes",
	"monkey",
	"monkeys",
	"bear",
	"bears",
	"penguin",
	"penguins",
	"zebra",
	"zebras",
	"dolphin",
	"dolphins",
	"squirrel",
	"squirrels",
	"rabbit",
	"rabbits",
	"owl",
	"owls",
	"horse",
	"horses",
	"cow",
	"cows",
	"sheep",
	"sheep",
	"pig",
	"pigs",
	"chicken",
	"chickens",
	"duck",
	"ducks",
	"goat",
	"goats",
	"deer",
	"deer",
	"fox",
	"foxes",
	"wolf",
	"wolves",
	"rhinoceros",
	"rhinoceroses",
	"whale",
	"whales",
	"dolphin",
	"dolphins",
	"shark",
	"sharks",
	"octopus",
	"octopuses",
	"seal",
	"seals",
	"polar bear",
	"polar bears",
	"kangaroo",
	"kangaroos",
	"hippopotamus",
	"hippopotamuses",
	"crocodile",
	"crocodiles",
	"platypus",
	"platypuses",
	"koala",
	"koalas",
	"sloth",
	"sloths",
	"chameleon",
	"chameleons",
	"lizard",
	"lizards",
	"camel",
	"camels",
	"bat",
	"bats",
	"parrot",
	"parrots",
	"panda",
	"pandas",
	"jaguar",
	"jaguars",
	"hamster",
	"hamsters",
	"hedgehog",
	"hedgehogs",
	"crow",
	"crows",
	"eagle",
	"eagles",
	"falcon",
	"falcons",
	"gazelle",
	"gazelles",
	"jaguarundi",
	"jaguarundis",
	"mongoose",
	"mongooses",
	"otter",
	"otters",
	"puma",
	"pumas",
	"red panda",
	"red pandas",
	"turtle",
	"turtles",
	"walrus",
	"walruses",
	"whale shark",
	"whale sharks",
	"yak",
	"yaks",
	"blue jay",
	"blue jays",
	"crab",
	"crabs",
]
export{animalWords}
const animalDescription = [
	"ferocious",
	"playful",
	"majestic",
	"sleek",
	"loyal",
	"adorable",
	"graceful",
	"fierce",
	"curious",
	"cunning",
	"gentle",
	"wild",
	"sociable",
	"mysterious",
	"intelligent",
	"striking",
	"endearing",
	"swift",
	"wise",
	"furry",
	"beautiful",
	"regal",
	"powerful",
	"nimble",
	"elusive",
	"savage",
	"magnificent",
	"sly",
	"colorful",
	"energetic",
	"charismatic",
	"humble",
	"strong",
	"muscular",
	"dainty",
	"sensual",
	"exotic",
	"graceful",
	"courageous",
	"dignified",
	"adorable",
	"mysterious",
	"enchanting",
	"fascinating",
	"poised",
	"swooping",
	"majestic",
	"glistening",
	"silent",
	"dynamic",
	"sleek",
	"endangered",
	"slippery",
	"camouflaged",
	"sensitive",
	"quick",
	"lean",
	"domesticated",
	"slim",
	"beautiful",
	"clever",
	"regal",
	"observant",
	"gleaming",
	"sharp",
	"muted",
	"patterned",
	"noble",
	"powerful",
	"furry",
	"energetic",
	"fussy",
	"sturdy",
	"friendly",
	"elegant",
	"loyal",
	"fierce",
	"friendly",
	"slow",
	"wild",
	"intriguing",
	"captivating",
	"muscular",
	"resourceful",
	"funny",
	"bewildered",
	"ornery",
	"hopeful",
	"sluggish",
	"helpless",
	"inquisitive",
	"silent",
	"drowsy",
]
export{animalDescription}
const animalQuestions = [
	"Why do elephants have such long trunks?",
	"What makes a chameleon change its color?",
	"How do birds fly?",
	"Why do cats purr?",
	"Where do dolphins sleep?",
	"What allows whales to communicate over long distances?",
	"How do bees make honey?",
	"Why do some animals hibernate?",
	"What gives a cheetah its speed?",
	"Why do dogs wag their tails?",
	"How do bats navigate in the dark?",
	"What makes a peacock's feathers so colorful?",
	"Why do kangaroos have pouches?",
	"Where do penguins live?",
	"What enables a spider to spin its web?",
	"Why do turtles have shells?",
	"How do ants communicate with each other?",
	"What gives a giraffe its long neck?",
	"Why do monkeys swing from trees?",
	"Where do bears go in the winter?",
	"What makes a camel so well suited for desert life?",
	"Why do wolves hunt in packs?",
	"How do owls see in the dark?",
	"What allows a salmon to swim upstream?",
	"Why do flamingos stand on one leg?",
	"Where do koalas get their nutrients from?",
	"What enables a horse to run so fast?",
	"Why do rabbits have such long ears?",
	"How do porcupines defend themselves?",
	"What gives a peacock its distinctive call?",
	"Why do ants carry food back to their nest?",
	"Where do polar bears live?",
	"What enables a pigeon to find its way home?",
	"How do squirrels remember where they bury their nuts?",
	"Why do zebras have stripes?",
	"What allows a scorpion to survive in extreme conditions?",
	"Why do elephants have such good memories?",
	"How do sharks detect their prey?",
	"What gives a gorilla its strength?",
	"Why do dolphins swim in pods?",
	"Where do crocodiles lay their eggs?",
	"What enables a parrot to mimic human speech?",
	"Why do bees dance?",
	"How do octopuses camouflage themselves?",
	"What allows a fish to breathe underwater?",
	"Why do hummingbirds have such fast wing beats?",
	"Where do bats hang upside down?",
	"What gives a sloth its slow pace?",
	"Why do butterflies migrate long distances?",
]
export{animalQuestions}
//животные
const loveWords = [
	"affection",
	"adore", 
	"passion", 
	"intimacy", 
	"devotion", 
	"romance", 
	"admire", 
	"cherish", 
	"tenderness", 
	"commitment",
	"endearment", 
	"infatuation", 
	"adoration", 
	"relationship", 
	"cuddle", 
	"heartbeat", 
	"connect", 
	"sweetheart", 
	"eternal", 
	"togetherness",
	"hug", 
	"kiss", 
	"couple", 
	"soulmate", 
	"attraction", 
	"loyalty", 
	"desire", 
	"caring", 
	"warmth", 
	"partner", 
	"compassion",
	"unity", 
	"passionate", 
	"beloved", 
	"flirt", 
	"appreciation", 
	"friendship", 
	"emotion", 
	"heavenly", 
	"support",
	"smile", 
	"trust",
	"bond", 
	"heartfelt", 
	"romantic", 
	"adorable", 
	"sincerity", 
	"feelings", 
	"butterflies", 
	"tender", 
	"understanding", 
	"respect",
	"embrace",  
	"lovable", 
	"gaze", 
	"genuine", 
	"harmony", 
	"kisses", 
	"passionately", 
	"belonging", 
	"sympathy",
	"sentiment", 
	"swoon", 
	"yearning", 
	"connection", 
	"amour", 
	"devoted", 
	"passionflower", 
	"gentle", 
	"relationship", 
	"poetry",
	"touch", 
	"instinct", 
	"tantalize", 
	"soulful", 
	"intense", 
	"fondness", 
	"heartstrings", 
	"flame", 
	"perfection", 
	"glimmer", 
	"sight",
	"kindness", 
	"yearn", 
	"heartbeat", 
	"flutter", 
	"craving", 
	"tenderness", 
	"bonds", 
	"courting", 
	"caring", 
	"ellipses", 
	"friendship", 
	"loyalty", 
	"cuddle", 
	"gazing", 
	"woo", 
	"tangible", 
	"sensuality", 
	"passionate", 
	"gaze", 
	"adoring", 
	"heartfelt",
	"gleam", 
	"obliging", "kindhearted", "crush", "tasting", "warmth", "voracity", "sweetheart", "amour", "pure",
	"intense", "passionate", "soulmate", "compassionate", "euphoria", "yearning", "longing", "rose", "beauty","hold",
	"affectionate", "whisper", "giggle", "delight", "future", "trusting", "happiness", "kissing", "allure", "forever", "spark",
	"connection", "intertwine", "softness", "intimate", "gaze", "cherished", "wish", "yearn", "pleasure", "glimpse", "rainbow",
	"stars", "moon", "waves", "forever", "comfort", "date", "promise", "princess", "marvel", "heartfelt", "date",
	"cherish", "cute", "destined", "flame", "hero", "amazing", "comfort", "devoted", "sparkle", "sunshine", "poem",
	"song", "treasure", "dance", "eternity", "fairy", "god", "opportunity", "intense", "hugging", "special", "passionate",
	"kissable", "scent", "moonlight", "starlight", "compromise", "openness", "gentle", "breathtaking", "serenity", "soulful",
	"unity", "solace", "paradise", "desire", "quiet", "enchanted", "daydream", "flowers", "gentleness", "rapture", "melody",
	"magnetic", "grateful", "union", "whispering", "harmony", "trustworthy", "cherub", "wonder", "dreams", "affectionate",
	"companion", "butterflies", "mesmerize", "captivating", "secret", "bliss", "sigh", "passionflower", "glow", "honey",
	"smitten", "inspire", "charm", "soulful", "fascinate", "sincere", "romantic", "poetry", "kaleidoscope", "adoration",
	"innocence", "glisten", "forever", "heavenly", "truth", "promise", "perfection", "intertwined", "magnetic",
	"tenderhearted", "contentment", "forever", "vision", "heartfelt", "caring", "embrace", "entwine", "enchanted", "guitar",
	"darling", "breathtaking", "enthrall", "softness", "gentle embrace", "heartwarming", "twinkle", "mesmerizing",
	"radiant", "blissful", "inspirational", "lover", "ecstasy", "warmth", "cherub", "sunset", "blanket", "caress",
	"luminous", "protection", "purity", "relationship", "emotion", "fondness", "delicate", "irresistible", "candlelight",
	"infinite", "teardrop", "harmony", "gaze", "savor", "treat", "charming", "complete", "forevermore", "gaze", "shimmer", "season", "innocent", "darling", "swift", "heartbeat", "sunset", "impression", "adventure", "anniversary",
	"blending", "breakable", "brilliantly", "capture", "caring", "cruise", "delight", "beyond", "softly", "always", "powerful",
	"celebrate", "constant", "creation", "endless", "everyday", "everything", "everlasting", "forever", "magnify", "relationship",
	"intertwined", "journey", "kindness", "life", "light", "longing", "loyal", "romance", "soul", "special", "sweetness", "together", "treasure", "want", "wonderful", "amazing", "lovely",
    "heartwarming", "authentic", "radiant", "sparkling", "gentle", "harmonious", "purest", "enchantment", "whispers", "intertwine",
    "pulses", "connected", "vibrant", "blissful", "sensational", "cherished", "delicious", "caring", "passionate", "delighted",
    "endearing", "angelic", "twinkle", "tender", "solace", "adoring", "glimpse", "dreamy", "captivating", "magic", "shining",
    "serene", "fascinated", "admiration", "soothing", "bountiful", "glowing", "tantalizing", "gentleness", "enchanted", "radiance",
    "adorable", "rapture", "majestic", "kissable", "resonate", "flicker", "joyful", "beloved", "mesmerize", "charming", 
    "cherub", "emotionally", "endless", "carefree", "passionately", "intimate", "sparkle", "sensual", "whispering", "harmony",
    "eternal", "desire", "comforting", "bliss", "ceaseless", "soulful", "kisses", "intrigue", "affectionate", "tenderness",
    "lush", "loyalty", "affirmation", "harbor", "reverence", "intertwined", "exquisite", "flourish", "sharing", "exhilarate",
    "caress", "vivid", "cherish", "romantic", "sweetheart", "caress", "love", "longing",
    "affection",
    "adore",
    "passion",
    "intimacy",
    "devotion",
    "romance",
    "admire",
    "cherish",
    "tenderness",
    "commitment",
    "endearment",
    "infatuation",
    "adoration",
    "relationship",
    "cuddle",
    "hearbeat",
    "connect",
    "sweetheart",
    "eternal",
    "togetherness",
    "hug",
    "kiss",
    "couple",
    "soulmate",
    "attraction",
    "loyalty",
    "desire",
    "caring",
    "warmth",
    "partner",
    "compassion",
    "unity",
    "passionate",
    "beloved",
    "flirt",
    "appreciation",
    "friendship",
    "emotion",
    "heavenly",
    "support",
    "smile",
    "trust",
    "bond",
    "heartfelt",
    "romantic",
    "adorable",
    "sincerity",
    "feelings",
    "butterflies",
    "tender",
    "understanding",
    "respect",
    "embrace",
    "twin flame",
    "lovable",
    "gaze",
    "genuine",
    "harmony",
    "kisses",
    "passionately",
    "belonging",
    "sympathy",
    "sentiment",
    "swoon",
    "yearning",
    "connection",
    "amour",
    "devoted",
    "passionflower",
    "gentle",
    "relationship",
    "poetry",
    "touch",
    "instinct",
    "tantalize",
    "soulful",
    "intense",
    "fondness",
    "heartstrings",
    "flame",
    "perfection",
    "glimmer",
    "sight",
    "kindness",
    "yearn",
    "heartbeat",
    "flutter",
    "craving",
    "tenderness",
    "bonds",
    "courting",
    "caring",
    "ellipses",
    "relationship",
    "friendship",
    "loyalty",
    "cuddle",
    "gazing",
    "woo",
    "tangible",
    "sensuality",
    "passionate",
    "gaze",
    "adoring",
    "heartfelt",
    "gleam",
    "obliging",
    "kindhearted",
    "crush",
    "tasting",
    "warmth",
    "voracity",
    "sweetheart",
    "amour",
    "pure",
    "intense"
]
export{loveWords}
const loveQuestions = [
	"Do you believe in love at first sight?",
	"What qualities do you look for in a partner?",
	"How do you show someone you care about them?",
	"Have you ever been in love?",
	"Do you believe in soulmates?",
	"What does love mean to you?",
	"How do you handle heartbreak?",
	"Do you think love can conquer all?",
	"What is the most romantic thing someone has done for you?",
	"What is your idea of a perfect date?",
	"Do you think love fades over time?",
	"How do you know when you are in love?",
	"How does love make you feel?",
	"What is the difference between love and infatuation?",
	"Are you a hopeless romantic?",
	"Do you believe in love that lasts a lifetime?",
	"What is the best love advice you've ever received?",
	"Do you think love is worth the risk of getting hurt?",
	"How do you define true love?",
	"What is the most important aspect of a successful relationship?",
	"Do you believe in second chances in love?",
	"What is your love language?",
	"Have you ever experienced unrequited love?",
	"What role does forgiveness play in a loving relationship?",
	"Do you think love can change a person?",
	"What is the greatest sacrifice you would make for love?",
	"How do you keep the spark alive in a long-term relationship?",
	"Have you ever had your heart broken?",
	"Do you believe in love that transcends time and distance?",
	"What is the most romantic gesture you've ever made for someone?",
	"How do you cope with a broken heart?",
	"How important is physical attraction in a relationship?",
	"Do you believe in love at any age?",
	"What is the most important lesson love has taught you?",
	"How do you know when it's time to let go of someone you love?",
	"Do you believe in love that is meant to be?",
	"What is the biggest misconception about love?",
	"What is the key to a lasting relationship?",
	"Do you think love is blind?",
	"What role does communication play in a loving relationship?",
	"What is your idea of true love?",
	"How do you handle conflicts in a relationship?",
	"Do you think love conquers all?",
	"What is the most important thing you can do for someone you love?",
]
export{loveQuestions}
//слова о чувствах и любви
const loveDescription = [
	"passionate",
	"affectionate",
	"tender",
	"romantic",
	"devoted",
	"compassionate",
	"adoring",
	"sweet",
	"intimate",
	"sincere",
	"empathetic",
	"sentimental",
	"caring",
	"gentle",
	"warm",
	"loving",
	"emotional",
	"tenderhearted",
	"committed",
	"tactile",
	"faithful",
	"supportive",
	"heartfelt",
	"endearing",
	"soulful",
	"friendly",
	"fond",
	"amorous",
	"kind",
	"touched",
	"sympathetic",
	"amiable",
	"judicious",
	"honest",
	"curious",
	"cozy",
	"enraptured",
	"unconditional",
	"delicate",
	"cherished",
	"deep",
	"affirming",
	"eager",
	"attentive",
	"glad",
	"blissful",
	"synergistic",
	"symbiotic",
	"engaged",
	"passionate",
	"intense",
	"excited",
	"joyful",
	"connected",
	"vulnerable",
	"sensitive",
	"nurturing",
	"sensual",
	"intertwined",
	"alluring",
	"attractive",
	"fascinating",
	"stimulating",
	"fulfilling",
	"playful",
	"amusing",
	"flirtatious",
	"tantalizing",
	"captivating",
	"energizing",
	"inspiring",
	"empowering",
	"reassuring",
	"rejuvenating",
	"remarkable",
	"serene",
	"magical",
	"enchanted",
	"poetic",
	"dreamy",
	"infatuated",
	"blissful",
	"beloved",
	"steady",
	"relaxed",
	"secure",
	"united",
	"devoted",
	"admired",
	"appreciated",
	"desired"
]
export{loveDescription}
//описание любви 
const musicGenres = [
	"alternative",
	"blues",
	"country",
	"dance",
	"electronic",
	"folk",
	"gospel",
	"hiphop",
	"indie",
	"jazz",
	"kpop",
	"metal",
	"newwave",
	"opera",
	"pop",
	"rap",
	"reggae",
	"salsa",
	"techno",
	"underground",
	"vocal",
	"world",
	"xylophone",
	"zydeco",
	"classical",
	"disco",
	"funk",
	"garage",
	"hardrock",
	"instrumental",
	"jungle",
	"klezmer",
	"motown",
	"orchestral",
	"punk",
	"raggaeton",
	"samba",
	"triphop",
	"urban",
	"waltz",
	"yodeling",
	"zydeco",
	"ambient",
	"breakbeat",
	"cabaret",
	"deathmetal",
	"emo",
	"fusion",
	"grunge",
	"heavymetal",
	"industrial",
	"jpop",
	"krishnacore",
	"lounge",
	"mambo",
	"nujazz",
	"psychedelic",
	"rockabilly",
	"spacerock",
	"tango",
	"trance",
	"vaporwave",
	"yéyé",
	"zouk",
	"afrobeat",
	"bhangra",
	"celtic",
	"doommetal",
	"electroswing",
	"fado",
	"grime",
	"hardcore",
	"italodisco",
	"jive",
	"kwaito",
	"lambada",
	"mathrock",
	"neosoul",
	"oi",
	"quartet",
	"rumba",
	"ska",
	"thrashmetal",
	"vikingmetal",
	"xtrabass",
	"zumba",
	"rock",
	"hyperpop",
	"chanson",
]
export{musicGenres}
const musicDescription = [
	"melodic",
	"rhythmic",
	"harmonious",
	"uplifting",
	"soulful",
	"captivating",
	"dynamic",
	"emotional",
	"energetic",
	"relaxing",
	"inspiring",
	"passionate",
	"groovy",
	"euphoric",
	"ethereal",
	"intense",
	"funky",
	"eclectic",
	"mellow",
	"sophisticated",
	"timeless",
	"creative",
	"vibrant",
	"lyrical",
	"expressive",
	"sensual",
	"rich",
	"sophisticated",
	"innovative",
	"haunting",
	"diverse",
	"engaging",
	"powerful",
	"hypnotic",
	"spiritual",
	"upbeat",
	"soothing",
	"dynamic",
	"elegant",
	"jazzy",
	"dreamy",
	"catchy",
	"unforgettable",
	"cinematic",
	"groovy",
	"joyful",
	"mystical",
	"captivating",
	"enchanting",
	"nostalgic",
	"zen",
	"transcendent",
	"fascinating",
	"uplifting",
	"immersive",
	"impassioned",
	"colorful",
	"uplifting",
	"complex",
	"sweeping",
	"intimate",
	"atmospheric",
	"evocative",
	"sultry",
	"energizing",
	"introspective",
	"quirky",
	"sophisticated",
	"hypnotic",
	"wild",
	"electric",
	"transformative",
	"fierce",
	"poetic",
	"breathtaking",
	"futuristic",
	"eclectic",
	"nostalgic",
	"uplifting",
	"reflective",
	"ecstatic",
	"sparkling",
	"mind-blowing",
	"trippy",
	"uplifting",
	"enigmatic",
	"soothing",
	"thought-provoking",
	"electrifying",
	"immersive"
]
export{musicDescription}
const musicQuestions = [
	"Do you like listening to music?",
	"Have you heard any good songs lately?",
	"What is your favorite music genre?",
	"Would you like to go to a concert?",
	"Do you play any musical instruments?",
	"Who is your favorite music artist?",
	"What kind of music do you listen to when you're sad?",
	"Have you ever been to a music festival?",
	"Do you prefer listening to music alone or with friends?",
	"What song always gets stuck in your head?",
	"Have you ever tried writing your own music?",
	"Do you like dancing to music?",
	"What do you think makes a song great?",
	"Do you listen to music while working or studying?",
	"What was the last album you listened to?",
	"Have you ever been to a karaoke night?",
	"Do you have a favorite music video?",
	"If you could learn to play any instrument, which one would you choose?",
	"What is the first concert you ever attended?",
	"Do you have a favorite movie soundtrack?",
	"Is there a particular song that reminds you of a special memory?",
	"Who is the most talented musician you know?",
	"Do you sing in the shower?",
	"What song gets you pumped up and excited?",
	"Do you listen to music to relax and unwind?",
	"Have you ever been to a music awards show?",
	"Do you have a favorite song that always makes you smile?",
	"What song would you choose for your theme song?",
	"Do you have a favorite musical? If so, which one?",
	"Who introduced you to your favorite music artist?",
	"What is the most recent song you added to your playlist?",
	"Do you like listening to live music performances?",
	"Do you have a favorite song to sing in the car?",
	"Have you ever cried while listening to a song?",
	"What is the weirdest music genre you've ever listened to?",
	"Do you have a favorite song lyric that resonates with you?",
	"What is your go-to song for a bad day?",
	"Have you ever attended a music workshop or class?",
	"Do you have a favorite song that always makes you feel nostalgic?",
	"What song would you choose for your wedding dance?",
	"What is the best concert you've ever been to?",
	"Do you have a favorite music festival memory?",
	"Do you like discovering new music artists?",
	"What is the most underrated song in your opinion?",
	"Have you ever met a famous musician?",
	"Do you have a favorite song for working out?",
	"What song do you always sing along to without fail?"
]
export{musicQuestions}
//жанры музыки и отношение к ним
const movieTitles = [
	"The Godfather",
	"Shawshank Redemption",
	"Pulp Fiction",
	"The Dark Knight",
	"Forrest Gump",
	"Titanic",
	"The Matrix",
	"Fight Club",
	"Inception",
	"Goodfellas",
	"The Silence of the Lambs",
	"Schindler's List",
	"The Lord of the Rings",
	"The Departed",
	"Gladiator",
	"Braveheart",
	"Jurassic Park",
	"The Shawshank Redemption",
	"The Green Mile",
	"The Lion King",
	"The Avengers",
	"Avatar",
	"Inglourious Basterds",
	"The Prestige",
	"The Revenant",
	"Django Unchained",
	"Interstellar",
	"The Godfather Part II",
	"The Dark Knight Rises",
	"The Social Network",
	"The Wolf of Wall Street",
	"Inglourious Basterds",
	"Whiplash",
	"Mad Max: Fury Road",
	"City of God",
	"The Grand Budapest Hotel",
	"The Terminator",
	"The Shawshank Redemption",
	"Eternal Sunshine of the Spotless Mind",
	"The Incredibles",
	"The Sixth Sense",
	"The Departed",
	"Se7en",
	"Inglourious Basterds",
	"The Princess Bride",
	"Rocky",
	"American Beauty",
	"The Truman Show",
	"The Social Network",
	"The Godfather Part II",
	"Saving Private Ryan",
	"The Dark Knight",
	"The Shining",
	"The Lion King",
	"Indiana Jones and the Last Crusade",
	"Jaws",
	"Scarface",
	"Alien",
	"The Big Lebowski",
	"The Departed",
	"Jurassic Park",
	"The Prestige",
	"There Will Be Blood",
	"The Shawshank Redemption",
	"The Dark Knight Rises",
	"Inception",
	"Django Unchained",
	"The Avengers",
	"Forrest Gump",
	"The Green Mile",
	"The Godfather",
	"Fight Club",
	"The Matrix",
	"Schindler's List",
	"Dunkirk",
	"Whiplash",
	"The Godfather Part II",
	"The Lord of the Rings",
	"The Silence of the Lambs",
	"Star Wars",
	"The Usual Suspects",
	"The Dark Knight",
	"The Godfather",
	"Goodfellas",
	"Pulp Fiction",
	"The Green Mile",
	"Inception",
	"Schindler's List",
	"The Lord of the Rings",
	"Forrest Gump",
	"The Shawshank Redemption",
	"The Matrix",
	"The Dark Knight Rises",
	"The Grand Budapest Hotel",
	"Gladiator",
	"Braveheart",
	"The Departed",
	"Mad Max: Fury Road",
	"The Godfather Part II",
	"The Prestige",
	"The Revenant",
	"Django Unchained",
	"Interstellar",
	"The Godfather Part II",
	"The Dark Knight Rises",
	"The Social Network",
	"The Wolf of Wall Street",
	"The Godfather",
	"Pulp Fiction",
	"The Dark Knight",
	"Forrest Gump",
	"Titanic",
	"The Matrix",
	"Fight Club",
	"Inception",
	"Goodfellas",
	"The Silence of the Lambs",
	"Schindler's List",
	"The Lord of the Rings",
	"The Departed",
	"Gladiator",
	"Braveheart",
	"Jurassic Park",
	"The Shawshank Redemption",
	"The Green Mile",
	"The Lion King",
	"The Avengers",
	"Avatar",
	"Inglourious Basterds",
	"The Prestige",
	"The Revenant",
	"Django Unchained",
	"Interstellar",
	"The Godfather Part II",
	"The Dark Knight Rises",
	"The Social Network",
	"The Wolf of Wall Street",
	"Inglourious Basterds",
	"Whiplash",
	"Mad Max: Fury Road",
	"City of God",
	"The Grand Budapest Hotel",
	"The Terminator",
	"The Shawshank Redemption",
	"Eternal Sunshine of the Spotless Mind",
	"The Incredibles",
	"The Sixth Sense",
	"The Departed",
	"Se7en",
	"Inglourious Basterds",
	"The Princess Bride",
	"Rocky",
	"American Beauty",
	"The Truman Show",
	"The Social Network",
	"The Godfather Part II",
	"Saving Private Ryan",
	"The Dark Knight",
	"The Shining",
	"The Lion King",
	"Indiana Jones and the Last Crusade",
	"Jaws",
	"Scarface",
	"Alien",
	"The Big Lebowski",
	"The Departed",
	"Jurassic Park",
	"The Prestige",
	"There Will Be Blood",
	"The Shawshank Redemption",
	"The Dark Knight Rises",
	"Inception",
	"Django Unchained",
	"The Light Between Oceans",
	"The Avengers",
	"Forrest Gump",
	"The Green Mile",
	"The Godfather",
	"Fight Club",
	"The Matrix",
	"Schindler's List",
	"Dunkirk",
	"Whiplash",
	"The Godfather Part II",
	"The Lord of the Rings",
	"The Silence of the Lambs",
	"Star Wars",
	"The Usual Suspects",
	"The Dark Knight",
	"The Godfather",
	"Goodfellas",
	"Pulp Fiction",
	"The Green Mile",
	"Inception",
	"Schindler's List",
	"The Lord of the Rings",
	"Forrest Gump",
	"The Shawshank Redemption",
	"The Matrix",
	"The Dark Knight Rises",
	"The Grand Budapest Hotel",
	"Gladiator",
	"Braveheart",
	"The Departed",
	"Mad Max: Fury Road",
	"The Godfather Part II",
	"The Prestige",
	"The Revenant",
	"Django Unchained",
	"Interstellar",
	"The Godfather Part II",
	"The Dark Knight Rises",
	"The Social Network",
	"The Wolf of Wall Street",
	"The Godfather",
	"Pulp Fiction",
	"The Dark Knight",
	"Forrest Gump",
	"Titanic",
	"The Matrix",
	"Fight Club",
	"Inception",
	"Goodfellas",
	"The Silence of the Lambs",
	"Schindler's List",
	"The Lord of the Rings",
	"The Departed",
	"Gladiator",
	"Braveheart",
	"Jurassic Park",
	"The Shawshank Redemption",
	"The Green Mile",
	"The Lion King",
	"The Avengers",
	"Avatar",
	"Inglourious Basterds",
	"The Prestige",
	"The Revenant",
	"Django Unchained",
	"Interstellar",
	"The Godfather Part II",
	"The Dark Knight Rises",
	"The Social Network",
	"The Wolf of Wall Street",
]
export{movieTitles}
const movieWords = [
	"movie","movies",
	"film","films",
	"cinema","cinemas",
	"кино","cinéma",
	"фильм","фильмы"
]
export{movieWords}
const movieMessages = [

]
export {movieMessages}
//список названий фильмов

const langNames = [
	"english", 
	"spanish", 
	"french", 
	"german", 
	"chinese", 
	"arabic", 
	"russian", 
	"hindi", 
	"portuguese", 
	"japanese", 
	"italian", 
	"korean", 
	"turkish", 
	"dutch", 
	"polish", 
	"swedish", 
	"vietnamese", 
	"indonesian", 
	"greek", 
	"thai", 
	"finnish", 
	"hebrew", 
	"czech", 
	"norwegian", 
	"danish", 
	"hungarian", 
	"romanian", 
	"ukrainian", 
	"bulgarian", 
	"croatian", 
	"slovak", 
	"serbian", 
	"malay", 
	"kurdish", 
	"bengali", 
	"tagalog", 
	"urdu", 
	"lithuanian", 
	"latvian", 
	"estonian", 
	"georgian", 
	"armenian",
	"icelandic", 
	"mongolian", 
	"sinhala", 
	"tamil", 
	"telugu", 
	"kannada", 
	"gujarati", 
	"marathi", 
	"punjabi", 
	"burmese", 
	"khmer", 
	"maltese", 
	"macedonian", 
	"albanian", 
	"bosnian", 
	"slovenian", 
	"kazakh", 
	"turkmen", 
	"azerbaijani", 
	"uzbek", 
	"tajik", 
	"moldovan", 
	"kyrghyz", 
	"tibetan", 
	"nepali", 
	"tibetan", 
	"aymara", 
	"quechua", 
	"guarani", 
	"fijian", 
	"tongan", 
	"samoan", 
	"maori", 
	"bislama", 
	"marshallese", 
	"palauan", 
	"yapese", 
	"chamorro", 
	"chuukese", 
	"kiribati", 
	"nauruan", 
	"tuvaluan", 
	"tokelauan", 
	"niuean", 
	"tahitian", 
	"rapanui", 
	"rarotongan", 
	"pitkern", 
	"hawaiian", 
	"flemish",
	"сhechen",
	"чеченский",
	
]
export{langNames}
const langNamesMessages = [
	"Smurf, I don't speak this language, but I wish I could learn it.",
	"Smurphy smurf smurf, but smurfity smurf smurf smurf.",
	"I'm a smurf, not a linguist, but I smurf this language interests me.",
	"Smurf-a-linguist? Not me. But curious? Definitely!",
	"Smurf-tastic! Another language I don't speak but wish I did.",
	"Not fluent, but definitely intrigued by this smurfing language.",
	"Smurf-a-dabble in this language? Maybe someday.",
	"Smurf me, I can't talk the talk in this language, but I'm curious.",
	"New language? No speaking smurfy for me, but I smurf the desire to learn.",
	"Smurf and smurf, I'm not a polyglot, but this language piques my interest.",
	"Nope, can't smurf in this language, but I wish I could!",
	"This language is smurfing alien to me, but I wish it wasn't!",
	"Don't speak this language, but a smurf can dream, right?",
	"I may not smurf this language, but it's on my smurf list to learn.",
	"I'm a smurf of few words in this language, but I'm keen to learn more.",
	"Speaka no linguistini, but I wanta learna this language.",
	"Smurf's up! I don't speak this language, but maybe one day.",
	"Smurf it! I don't speak this language, but wish I could.",
	"Smurfity smurf! I'm not fluent in this language, but it's on my smurf wishlist.",
	"No smurfing way I speak this language, but a smurf can dream.",
	"Smurf me sideways, this language is foreign to me, but intriguing.",
	"Not a smurfy speaker of this language, but someday, maybe.",
	"This language is a mystery to me, but a smurf can dream, right?",
	"Smurf it all! I'm not versed in this language, but I wish I was.",
	"Can't speak this language, but it's on my smurf radar.",
	"I may not speak this language, but the smurfiness is strong in me.",
	"Smurf my words, I don't speak this language, but I wish I did.",
	"Smurfing elusive this language may be, but I'm up for the challenge.",
	"I don't smurf the lingo, but I'm game to learn.",
	"No smurf in this language, but a smurf can dream, can't they?",
	"Smurf smurf no smurf, but the desire to learn is there.",
	"This language is a mystery to me, but I'd love to crack the code.",
	"Can't smurf my way through this language, but I sure wish I could.",
	"I'm smurfing clueless in this language, but I'm open to learning.",
	"Not a smurfy speaker of this language, but maybe one day.",
	"Speaking in tongues is not my forte, but learning new languages is.",
	"I may not speak this language, but the curiosity is smurf-strong in me.",
	"I don't smurf in this language, but I'm eager to smurf.",
	"Smurfity smurf, this language is beyond me, but I'm up for the challenge.",
	"I may not speak this language, but I'm smurfing interested.",
	"Smurfity smurf smurf, I don't speak this language, but I wish I did.",
	"I'm not a polyglot, but I'm intrigued by this language.",
	"Not fluent, but definitely keen on this language.",
	"Smurf my words, this language is foreign to me, but I wish it wasn't.",
	"I may not speak the language, but I'm all ears to learn it.",
	"No smurfing way I speak this language, but I'm smurfing interested.",
	"Smurf me sideways! I don't speak this language, but I'd love to.",
	"Smurfing heck, I don't speak this language, but I wish I did.",
	"Smurf me, this language isn't in my repertoire, but I'd love to add it.",
	"Can't smurf my way through this language, but I'm smurfing curious.",
	"I don't smurf in this language, but I'm smurfing interested.",
	"Can't smurf this language, but I'm all ears to learn it."
]
export{langNamesMessages}
const langNamesQuestions = [
	"Why do humans learn so many languages?",
	"What makes learning a new language so exciting?",
	"How do people decide which language to learn?",
	"What is the best way to learn a new language?",
	"Why do some people find language learning difficult?",
	"What role does culture play in language learning?",
	"Is it important to preserve endangered languages?",
	"How does learning a new language benefit the brain?",
	"What is the connection between language and identity?",
	"Why do some people have a natural talent for languages?",
	"Is it possible to become fluent in a language without living in a country where it's spoken?",
	"What motivates people to learn languages?",
	"How do languages evolve over time?",
	"What challenges do people face when learning a new language?",
	"Can technology make language learning easier?",
	"What impact does speaking multiple languages have on cognitive abilities?",
	"How do children learn language differently from adults?",
	"Why are some languages considered more difficult to learn than others?",
	"What is the importance of language diversity?",
	"How do language barriers affect communication?",
	"Why is it beneficial to be multilingual in today's world?",
	"Is language learning a lifelong process?",
	"What are the benefits of learning a second language from a young age?",
	"How do emotions impact language learning?",
	"What are the most effective language learning techniques?",
	"Why do some languages have more speakers than others?",
	"What are the advantages of being bilingual?",
	"How do languages influence each other?",
	"Why do accents vary from region to region?",
	"What is lost when a language becomes extinct?",
	"How do translators and interpreters bridge language barriers?",
	"What are the challenges of teaching a language to non-native speakers?",
	"Why do people enjoy learning languages as a hobby?",
	"What role do gestures and body language play in communication?",
	"How do dialects develop within a language?",
	"Why do some languages have more complex grammar rules?",
	"What impact does language have on thought processes?",
	"Is sign language considered a universal language?",
	"How do languages reflect societal values and norms?",
	"Why do some languages have unique writing systems?",
	"What is the role of language in preserving cultural traditions?",
	"How do language differences influence global interactions?",
	"Why do some languages have more words for certain concepts than others?",
	"What can studying ancient languages teach us about history?",
	"How do language policies shape education and government?",
	"Why do some languages borrow words from other languages?"
]
export{langNamesQuestions}

const rudeWords = [
	"shut",
	"stupid",
	"fool",
	"dirty",
	"git",
	"crazy",
	"screw","screws","screwing"
]

export{rudeWords}

const jokes = [
	"Why did the tomato turn red? Because it saw the salad dressing!",
	"I told my wife she should embrace her mistakes. She gave me a hug.",
	"I'm reading a book on the history of glue. I just can't seem to put it down!",
	"Why couldn't the bicycle stand up by itself? It was two tired!",
	"Parallel lines have so much in common. It's a shame they'll never meet.",
	"I would tell you a joke about pizza, but it's a little cheesy.",
	"Why don't scientists trust atoms? Because they make up everything!",
	"What did one wall say to the other wall? I'll meet you at the corner!",
	"I used to play piano by ear, but now I use my hands.",
	"Did you hear about the mathematician who's afraid of negative numbers? He'll stop at nothing to avoid them!",
	"Why do chicken coops only have two doors? Because if they had four, they'd be chicken sedans!",
	"I'm on a seafood diet. I see food and if it's from sea I eat it! It's Dylan MacDonald's joke!",
	"Why do bees have sticky hair? Because they use honeycombs!",
	"I was addicted to the hokey pokey, but I turned myself around.",
	"What do you call an alligator in a vest? An investigator!",
	"You can't run through a campground. You can only ran, because it's past tents!",
	"What's brown and sticky? A stick!",
	"Why can't you trust an atom? Because they make up everything!",
	"What do you call a fish wearing a crown? A kingfish!"
]
export {jokes}
const jokesWords = [
	"joke", "jokes",
	"fun", "funny",
	"gag", "gags",
	"prank", "pranks",
	"laugh", "laughs", "laughing",
	"farce",
	"anecdote", "anecdotes",
	"cheer", "cheers", "cheering",
	"story","stories",
]
export{jokesWords}