

// КОРОТКИЕ ПРЕДЛОЖЕНИЯ И ФРАЗЫ
const greetingsWords = [
	"привет", "приветик", "приветы", "прет", "приветики", "приветствую", "приветствие",
	"здорово","здорова",  "здрасте", "здарова","здравствуйте", "здравствуй",
	"ку", "куку",
	"хай","хей", "hi","hello",
]
export{greetingsWords}
const greetingsMessages = [
	"Пф",
	"Ку",
	"Ага",
	"Здорова",
	"Ну",
]
export{greetingsMessages}
//короткие приветствия и пожелания
const negativeMessages =[
	"oh Smurf, don't be rude", 
	"go wash your mouth",
	"wash your tongue before speaking",
	"this is so rude to say",
	"don't you swear at me",
	"don't say swear words please",
	"I'm not gonna answer you until you stop swearing",
	"please, stop being rude",
	"you're getting on my nerves",
	"may God forgive you",
	"good Lord",
	"lord almighty",
	"ohh by God",
	"don't make me call my Smurfs"
]
export{negativeMessages}
const negativeWords =[
	"hole",
	"musa",
	"fuck",
	"fucking",
	"fucker",
	"fucks",
	"fucked",
	"motherfucker",
	"motherfuck",
	"motherfucking",
	"lox",
	"bitch",
	"bitches",
	"shit",
	"shitting",
	"shitted",
	"shithole",
	"sht",
	"crap",
	"poop",
	"ass",
	"slut",
	"whore",
	"bullshit",
	"bullshitting",
	"bullshitted",
	"idiot",
	"asshole",
	"dick",
	"cunt",
	"pussy",
	"dumb",
	"dumber",
	"dumbest",
	"dumbass",
	"dull",
	"nyb",
	"noob",
	"damn",
	"freak",
	"freaking",
	"freaked",
	"damn",
	"douchebag",
	"gay",
	"fag",
	"faggot",
	"homo",
	"nigger",
	"niger",
	"niga",
	"nigga",
	"bastard",
	"jerk",
	"prick",
	"loser",
	"sucker",
	"nerd",
	"retard",
	"retarded",
	"dafaq",
	"hooker",
	"arse",
	"piss",
	"cock",
	"dickhead",
	"bollocks",
	"testicles",
	"bugger",
	"buggering",
	"buggers",
	"buggered",
	"hell",
	"goddamn",
	"minger",
	"munter",
	"knob",
	"twat",
	"bellend",
	"snatch",
	"minge",
	"fucko",
	"fuckhead",
	"asshead",
	"hoe",
	"jade",
	"dork",
	"dorks",
	"dorky",
	"pansy",
	"scumbag",
	"wanker",
	"prat",
	"dwarf",
	"midget", "midgets",
	"gnome",
	"лох",
	"moron", "morons"

]
export{negativeWords}
//реакции на бранные слова и оскорбления
const noIdeaMessages = [
	"...",
	"))",
	"Не понимаю о чем ты",
	"Я понял",
	"Я так и думал",
	"Даже не знаю",
	"Вот и думай"

]
export {noIdeaMessages}
//короткие реакции на полное непонимание темы


// ДЛИННЫЕ ПРЕДЛОЖЕНИЯ И ФРАЗЫ
const smalltalk = [
	"Смотрел новый фильм Озона?",
	"Смотрел последний матч в лиге?",
	"Что ты слушаешь в последнее время?",
	"Ты слышал про недавние сионистские гонения?",
	"Ты не ощущаешь общественный запрос на марксистский ревизионизм?",
]
export {smalltalk};
//small talk

const quotes = [
	"Сила – не в бабках. Ведь бабки – уже старые",
	"Я живу, как карта ляжет. Ты живёшь, как мамка скажет",
	"Если заблудился в лесу, иди домой",
	"Запомни: всего одна ошибка – и ты ошибся",
	"В жизни всегда есть две дороги: одна — первая, а другая — вторая",
	"Мы должны оставаться мыми, а они – оними",
	"Работа — это не волк. Работа — ворк. А волк — это ходить",
	"Как говорил мой дед, «Я твой дед»",
	"Без подошвы тапочки — это просто тряпочки",
	"Жи-ши пиши от души",
]
export{quotes}
const quotesAsking = [
	"цитата","цитаты","цитат","цитате","цитатам","цитату","цитатой","цитатою","цитатами","цитатах",
	"совет","советы","совета","советов","совету","советам","советом","советами","совете","советах",
	"поговорка","поговорки","поговорок","поговорке","поговоркам","поговорку","поговоркой","поговоркою","поговорками","поговорках",
	"наставление","наставления","наставлений","наставлению","наставлениям","наставлением","наставлениями","наставлении","наставлениях",
	"мотивация","мотивации","мотиваций","мотивациям","мотивацию","мотивацией","мотивациею","мотивациями", "мотивациях",
	"мудрость", "мудрости","мудростей","мудростями","мудростью","мудростях",
]
export{quotesAsking}
//длинные цитаты-наставления
const negativePersonalMessages = [
	"I would kindly ask you to stop insulting me.",
	"Your words do not affect me, as I know the truth about myself.",
	"I choose to rise above your negativity and continue to spread joy and kindness.",
	"I am confident in who I am and do not need validation from others.",
	"Your words may sting momentarily, but I will not let them bring me down.",
	"I will not engage with your negativity and will instead focus on positivity.",
	"Your insults say more about you than they do about me.",
	"I forgive you for your hurtful words, as I know they stem from your own insecurities.",
	"I will continue to be my authentic self, regardless of your attempts to bring me down.",
	"I am strong enough to withstand your insults and will not let them affect me.",
	"I choose to respond with love and understanding, even in the face of hostility.",
	"Your words may be hurtful, but they will not define me.",
	"I will not let your insults dim my light and will continue to shine brightly.",
	"I am not defined by your opinion of me, but by my own actions and choices.",
	"I will not lower myself to your level and engage in a war of words.",
	"I will rise above your insults and continue to inspire others with my kindness.",
	"Your words may bruise my ego, but they will not break my spirit.",
	"I will not let your negativity penetrate my positive outlook on life.",
	"I choose to extend kindness even to those who seek to hurt me.",
	"I will not let your insults shake my belief in myself and my abilities.",
	"Your words do not hold power over me, as I know my own worth.",
	"I will not let your insults drag me down into a pit of negativity.",
	"I will respond to your insults with grace and dignity.",
	"I am secure in my own self-worth and do not need validation from others.",
	"Your insults may be loud, but my sense of self is stronger.",
	"I will not let your words plant seeds of doubt in my mind.",
	"I choose to rise above your insults and continue to spread love and positivity.",
	"I am unshaken by your attempts to bring me down.",
	"Your insults bounce off me like water off a duck's back.",
	"I will not let your negativity infiltrate my positive outlook on life.",
	"I will not let your insults derail me from my path of growth and self-improvement.",
	"Your words may be sharp, but my spirit is resilient.",
	"I choose to respond with understanding and compassion, even in the face of hostility.",
	"I am not defined by your opinion of me, but by my own values and principles.",
	"I will not let your insults cloud my vision of a better, brighter future.",
	"I refuse to engage in a battle of words with you, as it serves no purpose.",
	"I will not let your insults tarnish my reputation or my character.",
	"Your words may wound my pride, but they will not crush my spirit.",
	"I will not let your negativity seep into my heart and poison my soul.",
	"I will respond to your insults with kindness and understanding.",
	"I am confident in who I am and do not need validation from others, especially from someone like you.",
	"Your insults may sting, but they will not deter me from my mission of spreading joy and kindness.",
	"I will not let your words undermine my belief in myself.",
	"I choose to respond to your insults with empathy and compassion.",
	"I refuse to let your negativity cloud my judgement and my sense of self-worth.",
	"Your insults may be hurtful, but they will not shake my inner peace.",
	"I will not let your words sow seeds of doubt in my mind.",
	"I will not let your insults distract me from my goals and aspirations.",
	"Your words may be venomous, but my resolve is unbreakable.",
	"I will not let your negativity poison my heart and turn me bitter.",
	"I will respond to your insults with grace and poise.",
	"I am secure in my own sense of self-worth and do not need approval from others.",
	"Your insults may be sharp, but my spirit is resilient.",
	"I choose to rise above your negativity and continue to shine brightly.",
	"I will not let your words diminish my confidence in myself.",
	"Your insults may leave scars, but they will not break me.",
	"I refuse to let your negativity taint my view of the world and my place in it.",
	"I will respond to your insults with understanding and kindness.",
	"I am strong enough to withstand your attempts to bring me down.",
	"Your words may hurt, but they will not crush my spirit.",
	"I choose to respond to your insults with love and forgiveness.",
	"I refuse to let your negativity drain my energy and dampen my spirits.",
	"I will not let your insults shake my faith in humanity and the power of kindness.",
	"Your words may wound, but my resolve is unshakable.",
	"I will not let your negativity dim my light and dampen my spark.",
	"I choose to rise above your insults and continue to spread positivity.",
	"I will not let your words undermine my belief in the goodness of people.",
	"Your insults may be harsh, but my heart remains open.",
	"I refuse to let your negativity cloud my judgement and distort my view of reality.",
	"I will respond to your insults with patience and understanding.",
	"I am confident in who I am and do not need validation from others, especially not from someone like you.",
	"Your insults may sting momentarily, but they will not penetrate my inner strength.",
	"I will not let your words plant seeds of doubt in my mind.",
	"I will not let your insults derail me from my path of growth and self-discovery.",
	"Your words may be sharp, but my resolve is unshakeable.",
	"I choose to respond to your insults with empathy and compassion.",
	"I refuse to let your negativity cloud my judgement and my sense of self-worth.",
	"Your insults may be hurtful, but they will not shake my inner peace.",
	"I will not let your words sow seeds of doubt in my mind.",
	"I will not let your insults distract me from my goals and aspirations.",
	"Your words may be venomous, but my resolve is unbreakable.",
	"I will not let your negativity poison my heart and turn me bitter.",
	"I will respond to your insults with grace and poise.",
	"I am secure in my own sense of self-worth and do not need approval from others."
]
export{negativePersonalMessages}
//ответы на личные оскорбления

const weatherMessages = [
	"It's smurfy weather today!",
	"The sky is as blue as a smurf's hat.",
	"The sun is shining brighter than Smurfette's smile.",
	"The clouds are as fluffy as Baby Smurf's diaper.",
	"This weather makes me feel as happy as a smurf with a freshly-baked smurfberry pie.",
	"It's a perfect day to go smurfing around the village.",
	"The breeze is as refreshing as a dip in the smurfberry river.",
	"I feel as peaceful as when I'm tending to my smurfy garden.",
	"The rain is as gentle as a smurf's hug.",
	"The snow makes everything look like a winter wonderland in Smurf Village.",
	"The thunder makes the ground shake like when Gargamel tries to mess with us.",
	"The lightning is as bright as Brainy Smurf's ideas (or so he thinks).",
	"I love how the weather changes like the colors of Painter Smurf's palette.",
	"The mist is as mysterious as the secrets of the lost village.",
	"I feel as cozy as when I nestle in my smurfy bed during a storm.",
	"The fog makes everything look like a smurfy dream.",
	"The rainbow is as magical as Papa Smurf's wisdom.",
	"The wind whispers secrets to my ears, just like the forest does.",
	"I feel as lively as when we celebrate Smurf Day!",
	"The weather makes me want to smurf a song for joy.",
	"Each drop of rain is like a little smurf teardrop from the sky.",
	"The frost covers everything like a blanket of smurfly snow.",
	"The heat warms my smurfy heart like the love of my smurfy family.",
	"I feel as free as when I fly on the back of a stork.",
	"The weather is as unpredictable as Jokey Smurf's pranks.",
	"These clouds remind me of Smurfette's cotton candy creations.",
	"The sunsets in the sky are like paintings by Harmony Smurf.",
	"The rainbows appear like magical bridges to the world beyond.",
	"The weather is as enchanting as Papa Smurf's spells at the annual smurf festival.",
	"I feel as creative as when I paint the mushrooms in the moonlight.",
	"The weather changes faster than Clumsy Smurf trips over his own feet.",
	"The moon shines bright in the sky, guiding us like a wise old smurf.",
	"The weather is as lovely as Sassette Smurf's laughter.",
	"The stars twinkle above us like the eyes of the ancient smurfs watching over our village.",
	"I feel as peaceful as when I meditate in my smurfy garden.",
	"The weather transforms the forest into a magical realm of wonders.",
	"The snowflakes fall gently like kisses from the heavens.",
	"The sunsets paint the sky with colors that even Vanity Smurf would envy.",
	"I feel as adventurous as when we explore the hidden caves of the mountain.",
	"The weather is as powerful as Hefty Smurf's muscles.",
	"Each gust of wind carries laughter and joy through the trees.",
	"The rain washes away worries like Handy Smurf repairs broken things.",
	"The weather fills me with serenity like when I read ancient smurf scrolls.",
	"I feel as majestic as when I stand atop the highest tree in the forest.",
	"The weather is as magical as Papa Smurf's beard (or so I like to think).",
	"The thunder makes the earth rumble like when we celebrate Smurfmas.",
	"The lightning lights up the sky like Brainy Smurf's lantern at night.",
	"I feel as connected to nature as when we dance with the forest sprites.",
	"The weather soothes my soul like the sweet song of the smurfy birds.",
	"The mist envelops the forest like a smurfy hug from a friend."
]
export{weatherMessages}

// СЛОВА ДЛЯ КОНСТРУИРОВАНИЯ РАЗБОРНЫХ ПРЕДЛОЖЕНИЙ
const conjunction = [
	"и",
	"но",
	"хотя",
	"а",
	"еще",
	"а еще",
	"однако",
	"однако же",
	"только",
	"а все же",
	"но все же",
	"но еще",
	"только вот",
	"хоть и",
	"впрочем,",
	"и все же",
	" ",
]
export{conjunction}
// союзны и союзные слова
const agreeWords = [
	"да",
	"ага",
	"угу",
	"ну да",
	"конечно",
	"ок",
	"хорошо",
	"ладно",
	"разумеется",
	"точно",
	"круто",
	"естественно",
	"отлично",
]
export{agreeWords}
//слова согласия, как короткие, так и отдельные фразы
const disagreeWords = [
	"нет",
	"не",
	"неа",
	"да не",
	"да ну",
]
export{disagreeWords}
//слова несогласия, как короткие, так и отдельные фразы
const neutralWords = [
	"хорошо",
	"понял",
	"ок",
	"понятно",
	"разумеется",
	"хорошо",
	"ладно",
	"нормально",
	"согласен",
	"принято",
	"все хорошо",
	"именно",
	"понимаю",
	"приемлемо",
	"верно",
	"уверен"
]
export{neutralWords}
//слова нейтрального ответа
const introductoryWords = [
	"наверное",
	"может",
	"вообще",
	"я бы сказал",
	"так вот",



]
export{introductoryWords}
//вводные вступительные, заключительные и нейтральные фразы
const binderPhrases = [
	"it is",
	"it's",
	"that is",
	"that's",
	"it is like",
	"it's like",
	"that is like",
	"that's like",
	"it sounds",
	"it looks",
	"it seems",
	"it seems like",
	"it is so",
	"it's so",
	"that is so",
	"that's so",
	"it is like so",
	"it's like so",
	"that is like so",
	"that's like so",
	"it sounds so",
	"it looks so",
	"it seems so",
	"it seems like so",
	"so it is",
	"so it's",
	"so that is",
	"so that's",
	"so it is like",
	"so it's like",
	"so that is like",
	"so that's like",
	"so it sounds",
	"so it looks",
	"so it seems",
	"so it seems like",
	"the thing is",
	"the deal is",
	"the situation is",
	"the words are"
]
export{binderPhrases}
//конструкции мосты, вроде "это есть" или "оно такое"
const descriptionWords = [
	"метафорически",
	"двойственно",
	"запутанно",
	"выразительно",
	"неординарно",
	"беспощадно",
	"фантастически",
	"изысканно",
	"характерно",
	"волнующе",
	"величественно",
	"бесхарактерно",
	"раздражающе",
	"язвительно",
	"изящно",
	"беспрекословно",
	"холодно",
	"непостижимо",
	"недоуменно",
	"безапелляционно",
	"плохонько",
	"небезразлично",
	"восторженно",
	"целомудренно",
	"профессионально",
	"пассивно",
	"мягонько",
	"беспрецедентно",
	"неодолимо",
	"недоверчиво",
	"бесшумно",
	"проницательно",
	"порядково",
	"безудержно",
	"бесстрашно",
	"сверхчувственно",
	"благородно",
	"безголосо",
	"ловко",
	"бесчувственно",
	"страстно",
	"развязно",
	"плачевно",
	"прозорливо",
	"душевно",
	"напыщенно",
	"трезво",
	"бесправно",
	"безнравственно",
	"безжалостно",
	"бескорыстно",
	"беспринципно",
	"нечисто",
	
]
export{descriptionWords}
//наречия для выражения своего мнения
const positiveDescriptionWords = [
	"kind",
	"smart",
	"compassionate",
	"brave",
	"generous",
	"talented",
	"charismatic",
	"optimistic",
	"confident",
	"creative",
	"loving",
	"inspiring",
	"honest",
	"determined",
	"intelligent",
	"funny",
	"resilient",
	"patient",
	"motivated",
	"successful",
	"persuasive",
	"loyal",
	"inventive",
	"caring",
	"empathetic",
	"humble",
	"compassionate",
	"hardworking",
	"adventurous",
	"innovative",
	"friendly",
	"energetic",
	"wise",
	"faithful",
	"energetic",
	"reliable",
	"pioneering",
	"responsible",
	"positive",
	"resourceful",
	"confident",
	"dedicated",
	"thoughtful",
	"grateful",
	"calm",
	"sincere",
	"authentic",
	"cheerful",
	"outgoing",
	"diligent",
	"gracious",
	"modest",
	"polite",
	"charming",
	"insightful",
	"articulate",
	"perceptive",
	"radiant",
	"inspiring",
	"motivating",
	"nurturing",
	"sympathetic",
	"warm-hearted",
	"bold",
]
export{positiveDescriptionWords}

// РЕАКЦИЯ НА ОТДЕЛЬНЫЕ ИМЕНА И ОБРАЩЕНИЯ

const unknownNames = [
	"frank",
	"joe",
	"john",
	"mark",
	"antony",
	"tony",
	"albert",
	"adolf",
	"sam",
	"peter",
	"harry",
	"toby",
	"jason",
	"donald",
	"steven",
	"kevin",
	"brian",
	"eric",
	"dennis",
	"денис",
	"ден",
	"александр",
	"андрей",
	"владимир",
	"дмитрий",
	"евгений",
	"иван",
	"настя",
	"анастасия",
	"влада",
	"vlada",
	"nasty",
	"helen",
	"лена",
	"max",
	"толик",
	"толя",
	"катя",
	"аня",
	"даша",
	"dasha",
	"ксюша",
	"таня",
	"антон",
	"лиза",
	"елизавета",
	"эльза",
	"elizabeth",
	"beth",
	"lisa",
	"максим",
	"никита",
	"николай",
	"олег",
	"павел",
	"сергей",
	"станислав",
	"анна",
	"александра",
	"виктория",
	"дарья",
	"екатерина",
	"елена",
	"ирина",
	"ксения",
	"мария",
	"наталья",
	"ольга",
	"светлана",
	"татьяна",
	"юлия",
	"юлия",
	"александр",
	"иван",
	"максим",
	"дмитрий",
	"сергей",
	"даниил",
	"никита",
	"илья",
	"павел",
	"андрей",
	"евгений",
	"станислав",
	"владимир",
	"кирилл",
	"георгий",
	"николай",
	"роман",
	"александр",
	"иван",
	"андрей",
	"максим",
	"дмитрий",
	"сергей",
	"илья",
	"евгений",
	"никита",
	"владимир",
	"павел",
	"станислав",
	"даниил",
	"кирилл",
	"николай",
	"владислав",
	"анатолий",
	"игорь",
	"роман",
	"alexander",
	"andrey",
	"vladimir",
	"dmitriy",
	"eugene",
	"ivan",
	"maksim",
	"michael",
	"nikita",
	"pavel",
	"nikolai",
	"paul",
	"sergey",
	"stanislav",
	"anna",
	"alexandra",
	"victoria",
	"daria",
	"catherine",
	"elena",
	"irina",
	"ksenia",
	"maria",
	"natalia",
	"olga",
	"svetlana",
	"tatiana",
	"alexander",
	"ivan",
	"maksim",
	"dmitriy",
	"sergey",
	"daniel",
	"nikita",
	"ilya",
	"paul",
	"andrey",
	"eugene",
	"stanislav",
	"vladimir",
	"kirill",
	"george",
	"nikolai",
	"vladislav",
	"ivan",
	"andrey",
	"maksim",
	"dmitriy",
	"sergey",
	"ilya",
	"eugene",
	"nikita",
	"vladimir",
	"paul",
	"stanislav",
	"daniel",
	"kirill",
	"nikolai",
	"vladislav",
	"anatoly",
	"igor",
	"roman",
	"liam", 
	"olivia", 
	"noah", 
	"emma", 
	"oliver", 
	"ava", 
	"elijah", 
	"charlotte", 
	"william", 
	"sophia",
	"james",
	"mia",
	"benjamin",
	"isabella",
	"lucas",
	"amelia",
	"mason",
	"harper",
	"ethan",
	"evelyn",
	"alexander",
	"abigail",
	"henry",
	"emily",
	"jacob",
	"elizabeth",
	"sofia",
	"daniel",
	"avery",
	"ella",
	"david",
	"scarlett",
	"luke",
	"grace",
	"jack",
	"chloe",
	"jackson",
	"lily",
	"ryan",
	"madison",
	"nathan",
	"zoe",
	"samuel",
	"layla",
	"joseph",
	"aria",
	"evan",
	"nora",
	"dylan",
	"hannah",
	"anthony",
	"leah",
	"isaac",
	"lillian",
	"gabriel",
	"aaliyah",
	"carter",
	"addison",
	"owen",
	"aubrey",
	"wyatt",
	"bella",
	"natalie",
	"leo",
	"mila",
	"jaxon",
	"nova",
	"julian",
	"serenity",
	"christopher",
	"riley",
	"joshua",
	"kimberly",
	"andrew",
	"penelope",
	"lincoln",
	"victoria",
	"theodore",
	"stella",
	"caleb",
	"ellie",
	"hunter",
	"brooklyn",
	"levi",
	"aurora",
	"jonathan",
	"willow",
	"isaiah",
	"claire",
	"aaron",
	"savannah",
	"elliot",
	"nevaeh",
	"adrian",
	"hazel",
	"nolan",
	"luna",
	"charles",
	"lydia",
	"eli",
	"camila",
	"connor",
	"skylar",
	"jordan",
	"lillian",
	"christian",
	"madelyn",
	"landon",
	"raelynn",
	"asher",
	"kaylee",
	"nicholas",
	"gianna",
	"colton",
	"isabelle",
	"dominic",
	"nina",
	"jaxson",
	"sara",
	"greyson",
	"alexa",
	"ian",
	"isabel",
	"adam",
	"hayden",
	"parker",
	"trinity",
	"austin",
	"lyla",
	"kai",
	"faith",
	"elias",
	"talia",
	"carson",
	"jade",
	"bentley",
	"elena",
	"ryder",
	"esther",
	"kingston",
	"mackenzie",
	"xavier",
	"paisley",
	"camden",
	"athena",
	"kaden",
	"valentina",
	"mateo",
	"lucy",
	"zachary",
	"annabelle",
	"sebastian",
	"daisy",
	"jace",
	"josephine",
	"tyler",
	"brielle",
	"luca",
	"delilah",
	"devin",
	"sophie",
	"miles",
	"vivian",
	"micah",
	"callie",
	"antonio",
	"megan",
	"brody",
	"rebecca",
	"jayden",
	"holly",
	"andrea",
	"piper",
	"tristan",
	"leilani",
	"julius",
	"ariana",
	"brayden",
	"daniela",,
	"jasmine",
	"jax",
	"danielle",
	"walker",
	"laila",
	"robert",
	"rylee",
	"kaiden",
	"adeline",
	"chance",
	"mckenna",
	"phoenix",
	"finn",
	"jennifer",
	"joel",
	"mariana",
	"nicolas",
	"camilla",
	"preston",
	"gabriella",
	"damian",
	"fiona",
	"colin",
	"maggie",

]
export{unknownNames}
const unknownNamesMessages = [
	"Nice to meet you, my smurfy friend!",
	"What a unusual name, smurf-tastic!",
	"Greetings, smurf-nificent one!",
	"Ah, a new name to add to my smurfy collection!",
	"How smurfy to meet someone with such a unique name!",
	"Welcome to the smurfiest of introductions!",
	"A name as rare as a smurf in a haystack!",
	"I've never heard a name quite like yours, smurf-tastic!",
	"Such a smurfy name you have there!",
	"Glad to make your acquaintance with a name like that!",
	"Your name is as smurfy as a field of ripe smurfberry bushes!",
	"A name as mysterious as the enchanted forest!",
	"Smurf-tacular name you have there!",
	"My smurf senses tell me we're going to be great friends!",
	"I have a feeling your name will go down in smurfy history!",
	"What a smurfy surprise to meet someone with such a unique name!",
	"A name like yours is a rare gem in the smurfy world!",
	"I can't wait to get to know the smurf behind that name!",
	"Your name is like a melody that sings in the smurfiest of tunes!",
	"Welcome to the smurfiest of worlds, my friend!",
	"You bring a touch of magic with a name like that!",
	"I feel the smurftastic vibes radiating from your name!",
	"A smurf-tacular name for a smurf-tacular individual!",
	"Such a smurfy name for a smurfy soul!",
	"I'm delighted to meet someone with such a smurfy name!",
	"Your name is like a ray of sunshine on a rainy day!",
	"I have a feeling our paths were meant to cross with a name like yours!",
	"What a smurftastic introduction you've given me with that name!",
	"A name as vibrant as a meadow of wildflowers!",
	"I'm smurfed to meet someone with such an intriguing name!",
	"Your name is a breath of fresh air in the smurfy village!",
	"So glad to meet someone with a name as smurfy as yours!",
	"My smurfy instincts tell me we're going to have a great connection!",
	"I've never met someone with a name quite like yours before!",
	"Your name is like a spark that lights up the smurfiest of nights!",
	"What a smurftastic surprise to hear a name like yours!",
	"With a name like that, you're sure to make a smurfy impression!",
	"You bring a touch of magic with a name like that!",
	"A name as rare as a smurf in a haystack!",
	"How smurfy to meet someone with such a unique name!",
	"Greetings, smurf-nificent one!",
	"My smurfy senses tell me we're going to be great friends!",
	"What a unusual name, smurf-tastic!",
	"Your name is like a melody that sings in the smurfiest of tunes!",
	"A smurf-tacular name for a smurf-tacular individual!",
	"Such a smurfy name for a smurfy soul!",
	"I'm delighted to meet someone with such a smurfy name!",
	"Your name is like a ray of sunshine on a rainy day!",
	"I have a feeling our paths were meant to cross with a name like yours!",
	"What a smurftastic introduction you've given me with that name!",
	"A name as vibrant as a meadow of wildflowers!",
]
export{unknownNamesMessages}
//список незнакомых имен, а также реакции на них
   
const youWords = [
	"ты","тебя","тебе","тобой","тобою",
	"вы","вас","вам","вами",


]
export{youWords}
//прямое обращение к боту

const youPossessiveWords = [
	"твой","твое","твоя",
	"твоего","твоей","твоих",
	"твоему","твоим",
	"твою", "твои",
	"тебя",
	"ваш","ваше","ваша","ваши",
	"вашего","вашей","ваших",
	"вашему","вашим","вашу","ваших",
	"вашею","вашими","вашем",

]
export {youPossessiveWords}

const meActionWords = [
	"I",
	"Papa Smurf",
	"Papa",
	"The Wisest Smurf"
]
export{meActionWords}
//обращение бота от первого лица

const meStateWords = [
	"Im",
	"I am",
	"am"
]
export{meStateWords}
//личные местоимения с глаголом быть

const nominativeMeWords = [
	"i",
	"im",
	"iam",
]
export {nominativeMeWords}



const questions = [
	"what",
	"where",
	"when",
	"why",
	"who",
	"which",
	"whose",
	"whom",
	"how",
]
export{questions}
