
//просто слова еда, продукты
const foodWords = [
	"еда","еды","еде","еду","едой","едою",
	"пища","пищи","пищ","пище","пищам","пищу","пищей","пищею","пищами","пищах",
	"блюдо","блюда","блюд","блюду","блюдам","блюдом","блюдами","блюде","блюдах",
	"продукт","продукты","продукта","продуктов","продукту","продуктам","продуктом","продуктами","продукте","продуктах",
]
export{foodWords}


//названия блюд, овощей, фруктов
const foodNames = [
	"трубочка","трубочки","трубочек","трубочке","трубочкам","трубочку","трубочкой","трубочкою","трубочками","трубочке","трубочках",
	"вафля","вафли","вафель","вафле","вафлям","вафлю","вафлей","вафлею","вафлями","вафлях",
	"пицца","пиццы","пицц","пицце","пиццам","пиццу","пиццей","пиццею","пиццами","пиццах",
	"масло","масла","масел","маслу","маслам","маслом","маслами","масле","маслах",
	"оладьи", "оладья","оладий","оладье","оладьям","оладью","оладьей","оладьею","оладьями","оладьях",
	"блин","блины","блина","блинов","блину","блинам","блином","блинами","блине","блинах",
	"ягода", "ягоды","ягод","ягоде","ягодам","ягоду","ягодой","ягодою","ягодами","ягодах",
	
	"fries",
	"burger", "burgeers",
	"steak", "steaks",
	"potato", "potatoes",
	"brownie",
	"sardines",
	"sardine",
	"cюрстрёмминг",
	"cюрстремминг",
	"surströmming",
	"cola",
	"soda",
	"rice",
	"pasta",
	"almond",
	"artichoke",
	"noodles",
	"tuna",
	"avocado",
	"roll",
	"bacon",
	"beans",
	"bagels",
	"bbq",
	"beer",
	"bisque",
	"bread",
	"broccoli",
	"buritto",
	"cabbage",
	"cake",
	"cheese",
	"chicken",
	"chips",
	"chocolate",
	"cookies",
	"corn",
	'crab',
	'curry', 
	'cereal', 
	'duck', 
	'donut', 
	'egg', 
	'muffins', 
	'muffin', 
	'sushi', 
	'fish', 
	'toast', 
	'garlic', 
	'ginger', 
	'goose', 
	'grapes', 
	'cracker', 
	'ham', 
	'hamburger', 
	'cheeseburger', 
	'honey', 
	'stew', 
	'jam', 
	'jalapeño', 
	'ketchup', 
	'kiwi', 
	'kidney', 
	'kingfish', 
	'lobster', 
	'lamb', 
	'linguine', 
	'lasagna', 
	'meatballs', 
	'moose', 
	'milk', 
	'milkshake', 
	'pepperoni', 
	'spinach', 
	'spaghetti', 
	'walnuts', 
	'walnut', 
	'yogurt', 
	'zapiekanka', 
	'zongzi', 
	'zoni', 
	'zuccotto', 
	"cakes",
	"apple", "apples",
	"banana", "bananas",
	"orange", "oranges",
	"strawberry", "strawberries",
	"pear", "pears",
	"grape", "grapes",
	"watermelon", "watermelons",
	"kiwi", "kiwis",
	"peach", "peaches",
	"mango", "mangos",
	"lemon", "lemons",
	"lime", "limes",
	"cherry", "cherries",
	"blueberry", "blueberries",
	"pineapple", "pineapples",
	"apricot", "apricots",
	"plum", "plums",
	"grapefruit", "grapefruits",
	"pomegranate", "pomegranates",
	"melon", "melons",
	"strawberries", "strawberry",
	"raspberries", "raspberry",
	"blackberry", "blackberries",
	"kiwi", "kiwis",
	"cantaloupe", "cantaloupes",
	"nectarine", "nectarines",
	"tangerine", "tangerines",
	"fig", "figs",
	"lime", "limes",
	"coconut", "coconuts",
	"tomato", "tomatoes",
	"cucumber", "cucumbers",
	"carrot", "carrots",
	"lettuce", "lettuces",
	"pepper", "peppers",
	"potato", "potatoes",
	"onion", "onions",
	"pea", "peas",
	"bean", "beans",
	"broccoli", "broccolis",
	"zucchini", "zucchinis",
	"spinach", "spinachs",
	"garlic", "garlics",
	"squash", "squashes",
	"cabbage", "cabbages",
	"celery", "celeries",
	"eggplant", "eggplants",
	"mushroom", "mushrooms",
	"asparagus", "asparaguses",
	"avocado", "avocados",
	"artichoke", "artichokes",
	"pepper", "peppers",
	"corn", "corns",
	"radish", "radishes",
	"green bean", "green beans",
	"brussels sprout", "brussels sprouts",
	"cauliflower", "cauliflowers",
	"beet", "beets",
	"leek", "leeks",
	"parsnip", "parsnips",
	"lemon", "lemons",
	"pomelo", "pomelos",
	"plantain", "plantains",
	"kale", "kales",
	"guava", "guavas",
	"locust", "locusts",
	"kumquat", "kumquats",
	"radicchio", "radicchios",
	"endive", "endives",
	"beef",
]
export{foodNames}

//описание для еды
const foodDescription = [
	"аппетитно",
	"вкусно",
	"сочно",
	"ароматно",
	"нежно",
	"сладко",
	"остро",
	"горько",
	"сладенько",
	"пряно",
	"смачно",
	"сладостно",
	"жирно",
	"горьковато",
	"пресно",
	"изысканно",
]
export{foodDescription}

//вопросы про еду
const foodQuestions = [
	"What's your favorite type of cuisine?",
	"Do you prefer sweet or savory dishes?",
	"Have you ever tried cooking a new recipe?",
	"Do you enjoy spicy food?",
	"What's the weirdest food you've ever tried?",
	"Are you a fan of fast food?",
	"Do you like to eat out or cook at home?",
	"Have you ever been to a food festival?",
	"Do you like to experiment with new flavors?",
	"What's your go-to comfort food?",
	"Do you have any dietary restrictions?",
	"Have you ever tried a food challenge?",
	"Do you enjoy trying different foods from around the world?",
	"What's your favorite dessert?",
	"Do you like to snack throughout the day?",
	"Have you ever eaten a dish that was too spicy for you?",
	"Do you like to pair food with wine or other beverages?",
	"Do you have a favorite food blogger or chef?",
	"What's your opinion on fusion cuisine?",
	"Do you believe in the saying 'you are what you eat'?",
	"Have you ever cooked for a large group of people?",
	"Do you follow any food trends?",
	"What's your favorite breakfast food?",
	"Do you like to pack your own lunch for work/school?",
	"Have you ever made your own pasta or bread from scratch?",
	"Do you enjoy trying street food when traveling?",
	"What's your favorite food holiday or celebration?",
	"Do you like to host dinner parties?",
	"Have you ever tried a food from a different culture that you didn't like?",
	"Do you like to donate to food banks or charities?",
	"What's your opinion on food waste?",
	"Do you have a favorite food-related movie or TV show?",
	"Is there a dish that reminds you of your childhood?",
	"Have you ever taken a cooking class?",
	"Do you have a favorite restaurant that you frequent?",
	"What's your go-to meal when you don't feel like cooking?",
	"Do you have a favorite food-related memory?",
	"Are you a fan of food documentaries?",
	"What's the most exotic food you've ever tried?",
	"Do you meal prep for the week ahead?",
	"Have you ever had a food allergy scare?",
	"Do you enjoy gardening or growing your own produce?",
	"What's your favorite food-related quote?",
	"Do you like to try new food products or brands?",
	"Have you ever participated in a food tasting event?",
	"Do you enjoy cooking with fresh ingredients or do you prefer convenience foods?",
]
export{foodQuestions}
//описание еды